language: java
script:
    - ant compile
    - ant test
    - sudo apt-get install sshpass
    - sshpass -p "e.pajouheshgar@gmail.com" scp -o StrictHostKeyChecking=no server.jar 94109143@198.144.184.34:/home/94109143/
    - sshpass -p "e.pajouheshgar@gmail.com" ssh 94109143@198.144.184.34 pkill java
    - sshpass -p "e.pajouheshgar@gmail.com" ssh 94109143@198.144.184.34 nohup java -jar /home/94109143/server.jar &
